[package]
name = "rcopy-storage"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
chrono.workspace = true
rcopy-core = { path = "../core" }
rusqlite.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
